// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

type SupabaseClient = ReturnType<typeof createClient<Database>>;

function readEnv(name: string) {
  const viteEnv = typeof import.meta !== 'undefined' ? import.meta.env?.[name] : undefined;
  const nodeEnv = typeof process !== 'undefined' ? process.env?.[name] : undefined;
  const value = viteEnv || nodeEnv || '';
  if (typeof value !== 'string') return '';

  let cleaned = value.trim();
  if (/^[A-Z0-9_]+\s*=/.test(cleaned)) {
    cleaned = cleaned.slice(cleaned.indexOf('=') + 1).trim();
  }

  while (
    (cleaned.startsWith('"') && cleaned.endsWith('"')) ||
    (cleaned.startsWith("'") && cleaned.endsWith("'"))
  ) {
    cleaned = cleaned.slice(1, -1).trim();
  }

  return cleaned;
}

function readSupabaseUrl() {
  const raw = readEnv('VITE_SUPABASE_URL') || readEnv('SUPABASE_URL');
  const withoutRestPath = raw.replace(/\/rest\/v1\/?$/, '').replace(/\/+$/, '');

  try {
    const url = new URL(withoutRestPath);
    if (!['https:', 'http:'].includes(url.protocol)) return '';
    return url.origin;
  } catch {
    return '';
  }
}

function readSupabasePublishableKey() {
  return (
    readEnv('VITE_SUPABASE_PUBLISHABLE_KEY') ||
    readEnv('VITE_SUPABASE_ANON_KEY') ||
    readEnv('SUPABASE_PUBLISHABLE_KEY') ||
    readEnv('SUPABASE_ANON_KEY')
  );
}

function createOfflineSupabaseClient(): SupabaseClient {
  const noSession = Promise.resolve({ data: { session: null }, error: null });
  const noUser = Promise.resolve({ data: { user: null }, error: null });
  const subscription = { unsubscribe() {} };

  const query = {
    select: () => query,
    update: () => query,
    insert: () => query,
    upsert: () => query,
    delete: () => query,
    eq: () => query,
    maybeSingle: () => Promise.resolve({ data: null, error: null }),
    single: () => Promise.resolve({ data: null, error: null }),
  };

  return {
    auth: {
      getSession: () => noSession,
      getUser: () => noUser,
      onAuthStateChange: () => ({ data: { subscription } }),
      signOut: () => Promise.resolve({ error: null }),
      signUp: () => Promise.resolve({
        data: { user: null, session: null },
        error: new Error('Supabase is not configured. Add the Supabase environment variables to enable login.'),
      }),
      signInWithPassword: () => Promise.resolve({
        data: { user: null, session: null },
        error: new Error('Supabase is not configured. Add the Supabase environment variables to enable login.'),
      }),
      setSession: () => noSession,
    },
    from: () => query,
  } as unknown as SupabaseClient;
}

function createSupabaseClient() {
  const SUPABASE_URL = readSupabaseUrl();
  const SUPABASE_PUBLISHABLE_KEY = readSupabasePublishableKey();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn('[Supabase] Environment variables are missing or invalid. Running with local-only game saves and login disabled.');
    return createOfflineSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
