// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function readEnv(name: string) {
  const value = process.env[name] || '';
  let cleaned = value.trim();

  if (/^[A-Z0-9_]+\s*=/.test(cleaned)) {
    cleaned = cleaned.slice(cleaned.indexOf('=') + 1).trim();
  }

  while (
    (cleaned.startsWith('"') && cleaned.endsWith('"')) ||
    (cleaned.startsWith("'") && cleaned.endsWith("'"))
  ) {
    cleaned = cleaned.slice(1, -1).trim();
  }

  return cleaned;
}

function readSupabaseUrl() {
  const raw = readEnv('SUPABASE_URL') || readEnv('VITE_SUPABASE_URL');
  const extracted = raw.match(/https?:\/\/[a-z0-9-]+\.supabase\.co(?:\/rest\/v1)?/i)?.[0] ?? raw;
  const withoutRestPath = extracted.replace(/\/rest\/v1\/?$/, '').replace(/\/+$/, '');

  try {
    const url = new URL(withoutRestPath);
    if (!['https:', 'http:'].includes(url.protocol)) return '';
    return url.origin;
  } catch {
    return '';
  }
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = readSupabaseUrl();
  const SUPABASE_SERVICE_ROLE_KEY = readEnv('SUPABASE_SERVICE_ROLE_KEY');

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL or VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing or invalid Supabase environment variable(s): ${missing.join(', ')}. Add the Supabase project URL and service role key for admin server actions.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
